name: 'reservation_app'

services:

  postgres:
    # jaki image ma byc uzyty w tyn kontenerze
    image: 'postgres:14.7'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=reservation_DB'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    # pozwala na przechowywanie danych poza filesystemem kontenera, dzieki czemu po jego wylaczeniu nie tracimy danych
    volumes:
      - 'postgres_data:/var/lib/postgres/data'


  reservation_app:
    # automatyczne budowanie obrazu {context-określenie root-dira dla dockera; dockerfile- nazwa dokcerfila }
    build:
      context: './'
      dockerfile: 'Docker/Dockerfile'
    container_name: 'reservation_app'
    # depends_on - które kontenery zostaną włąaczone najpierw
    depends_on:
      - 'postgres'
    # zmienne srodowiskowe
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/reservation_DB'
      - 'SPRING_DATASOURCE_USERNAME=user'
      - 'SPRING_DATASOURCE-PASSWORD=password'
    # z którego w kontenerze na jaki na localhost
    ports:
      - '8080:8080'


volumes:
  postgres_data: